# Generated by Django 4.1.7 on 2023-03-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='vid',
            field=models.FileField(default=4, upload_to='files/'),
            preserve_default=False,
        ),
    ]
