# Generated by Django 4.1.7 on 2023-03-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.AddField(
            model_name='post',
            name='last_modified_date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
