# Generated by Django 4.1.7 on 2023-03-09 02:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_comment_photo_comment_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='vid',
            field=models.FileField(null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
