# Generated by Django 4.1.7 on 2023-03-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_rename_date_post_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creation_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='last_modified_date',
            new_name='date_modified',
        ),
    ]
