# Generated by Django 4.1.7 on 2023-03-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_alter_comment_vid'),
        ('Posts', '0005_comment_photo_alter_comment_post_alter_comment_user_and_more'),
    ]

    operations = [
    ]
