# Generated by Django 4.1.7 on 2023-03-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_merge_20230313_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
