# Generated by Django 4.1.7 on 2023-03-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
