# Generated by Django 4.1.7 on 2023-03-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
