# Generated by Django 4.1.7 on 2023-03-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe_ID',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe_ID',
            field=models.ManyToManyField(related_name='Ingredients', to='Recipes.recipe'),
        ),
    ]
