# Generated by Django 4.1.7 on 2023-03-28 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0002_remove_ingredient_recipe_id_ingredient_recipe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='step_list',
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('avatar', models.ImageField(blank=True, default=None, upload_to='images/steps/')),
                ('description', models.CharField(max_length=250)),
                ('recipe_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Steps', to='Recipes.recipe')),
            ],
        ),
    ]
