# Generated by Django 4.1.7 on 2023-03-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0003_remove_recipe_step_list_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='avatar',
            new_name='image',
        ),
    ]
