# Generated by Django 4.1.7 on 2023-03-28 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0004_rename_avatar_step_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='recipe_ID',
        ),
        migrations.AlterField(
            model_name='step',
            name='recipe_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_list', to='Recipes.recipe'),
        ),
        migrations.AddField(
            model_name='diet',
            name='recipe_ID',
            field=models.ManyToManyField(related_name='diets', to='Recipes.recipe'),
        ),
    ]
